title: Magic Mirror
description: A Mirror Display

source: "public"

author: Rory Claasen
author_url: "http://roryclaasen.me"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  startings: [html, head, body]

sass:
   sass_dir: assets/style
   style: :compressed

module:
    weather:
        visible: true
        latitude: "50.892206"
        longitude: "-0.957955"
    clock:
        visible: true
    calender:
        visible: true
        maxEvents: 9
